# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9eccf8aa78b1d3ec10a2c97b8ef59f4bbe92111f771a92fa0e20826c1889b462cdc067933e3873e1720ad09121b729ad10a133cfc8c970b02ab51c2524be792

test:
  secret_key_base: 229ee55b9103bd0171d9019222328a81df05ce525aeeb8454621e17c589a26e5376a144513e0b1b99e30bb0eb841e5387f055792e7a2684e8fa02c81a9234313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
